---
title: "iteration_and_listcol"
author: "Stephen Lewandowski"
date: "October 30, 2018"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

library(tidyverse)
library(rvest)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Lists

```{r}
l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary     = summary(rnorm(1000)))
l
```


## for loops

```{r}
df = data_frame(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

is.list(df)
df[[1]]
df[[2]]
```


Let's get a function.

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

Apply function to dataframe

```{r}

mean_and_sd(df[[1]])
mean_and_sd(df[[2]])
mean_and_sd(df[[3]])
```

Write a for loop

```{r}
output = vector("list", length = 4)
output

output[[1]] = mean_and_sd(df[[1]])
output[[2]] = mean_and_sd(df[[2]])
output[[3]] = mean_and_sd(df[[3]])

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(df[[i]])

}
output
```

Replace `for` loop with `map`

```{r}

output = map(df, mean_and_sd)
output
```

Let's try a different function

```{r}
output = map(df, median)
output

output = map(df, summary)
output
```

## map variant

```{r}

output = map_df(df, mean_and_sd)
output

output = map_dbl(df, median)
output
```

## code syntax

be clear about arguments

```{r}
output = map(.x = df, ~ mean_and_sd(x = .x))
output
```

## Revisit Napolean Dynamite

```{r}
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  data_frame(title, stars, text)
}

url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_urls = str_c(url_base, 1:5)

vec_urls

# check that function works
read_page_reviews(vec_urls[[1]])
read_page_reviews(vec_urls[[2]])

reviews = map(vec_urls, read_page_reviews)
reviews
```

## List cols...

```{r}
library(rnoaa)

weather = 
  meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather
```

```{r}
weather_nest = 
  nest(weather, date:tmin)

weather_nest
```



```{r}
weather_nest %>% 
  pull(name)

weather_nest %>% 
  pull(id)

weather_nest %>% 
  pull(data)
```

Unnesting...

```{r}
weather_nest %>% 
  unnest

```

look at LC elements

```{r}
weather_nest$data[[1]] %>%
  skimr::skim()
```

Fit a location-specific regression ..

```{r}
lm(tmax ~tmin, data = weather_nest$data[[1]])
lm(tmax ~tmin, data = weather_nest$data[[2]])
lm(tmax ~tmin, data = weather_nest$data[[3]])
```

Write a function!

```{r}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}
```

```{r}
weather_lm(df = weather_nest$data[[1]])
```

```{r}
map(weather_nest$data, weather_lm)
```

Save output as a new list column...

```{r}
weather_nest %>% 
  mutate(lm_results = map(data, weather_lm))

```


More examples...
```{r}
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  review_titles = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  review_stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  review_text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}



url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

urls = str_c(url_base, 1:5)


```

```{r}
tibble(
    page = 1:5,
    url = str_c(url_base, page)
) %>% 
  mutate(reviews = map(url, read_page_reviews)) %>% 
  unnest()

```

